In [1]:
import torch

In [3]:
x = torch.empty(5, 3)

In [4]:
x

tensor([[0.0000e+00, 2.5244e-29, 5.9006e+29],
        [2.8685e-42, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
x = torch.rand(5, 3)

In [6]:
x

tensor([[0.9864, 0.0776, 0.8210],
        [0.3385, 0.7273, 0.6828],
        [0.3886, 0.1882, 0.9428],
        [0.4214, 0.1868, 0.0799],
        [0.4475, 0.8557, 0.6006]])

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([5.5, 3])

In [9]:
x

tensor([5.5000, 3.0000])

In [10]:
x = x.new_ones(5, 3)

In [11]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
x = x.new_ones(5, 3, dtype=torch.double)

In [15]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x.shape

torch.Size([5, 3])

In [17]:
x.size()

torch.Size([5, 3])

In [18]:
y = torch.rand(5, 3)

In [19]:
y

tensor([[0.5987, 0.0904, 0.9187],
        [0.8981, 0.2772, 0.0687],
        [0.3948, 0.9215, 0.9150],
        [0.3693, 0.4504, 0.8745],
        [0.0798, 0.2771, 0.1285]])

In [20]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
x + y

tensor([[1.5987, 1.0904, 1.9187],
        [1.8981, 1.2772, 1.0687],
        [1.3948, 1.9215, 1.9150],
        [1.3693, 1.4504, 1.8745],
        [1.0798, 1.2771, 1.1285]], dtype=torch.float64)

In [22]:
torch.add(x, y)

tensor([[1.5987, 1.0904, 1.9187],
        [1.8981, 1.2772, 1.0687],
        [1.3948, 1.9215, 1.9150],
        [1.3693, 1.4504, 1.8745],
        [1.0798, 1.2771, 1.1285]], dtype=torch.float64)

In [24]:
y[:, 1]

tensor([0.0904, 0.2772, 0.9215, 0.4504, 0.2771])

In [29]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x, y, z

(tensor([[-0.4022,  0.0648, -1.2390, -0.5567],
         [ 0.5426, -1.3473,  1.1213, -1.2914],
         [ 1.1213,  1.6122,  0.5808,  0.6207],
         [ 0.4763, -1.1985, -1.4699, -1.5439]]),
 tensor([-0.4022,  0.0648, -1.2390, -0.5567,  0.5426, -1.3473,  1.1213, -1.2914,
          1.1213,  1.6122,  0.5808,  0.6207,  0.4763, -1.1985, -1.4699, -1.5439]),
 tensor([[-0.4022,  0.0648, -1.2390, -0.5567,  0.5426, -1.3473,  1.1213, -1.2914],
         [ 1.1213,  1.6122,  0.5808,  0.6207,  0.4763, -1.1985, -1.4699, -1.5439]]))

In [30]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [31]:
x = torch.randn(1)
x, x.item()

(tensor([-1.8533]), -1.8533191680908203)

In [32]:
x = torch.randn(5, 3)
y = x.numpy()
x, y

(tensor([[ 0.0739, -1.1913,  0.0018],
         [ 1.0622, -0.8036, -0.4821],
         [ 1.0124,  0.0306, -0.9023],
         [ 0.1317,  1.1636, -0.2151],
         [-1.0047,  0.8043,  0.6616]]),
 array([[ 0.07391316, -1.1913304 ,  0.00179395],
        [ 1.062247  , -0.8036002 , -0.48214287],
        [ 1.0123531 ,  0.03060714, -0.9022904 ],
        [ 0.13168094,  1.1636351 , -0.21511465],
        [-1.0046542 ,  0.8042948 ,  0.66162485]], dtype=float32))

In [33]:
import numpy as np

In [37]:
a = np.ones(5)
b = torch.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [38]:
torch.cuda.is_available()

False