In [22]:
import torch

In [23]:
x = torch.ones(2, 2, requires_grad=True)

In [24]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [25]:
y = x + 2

In [26]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [27]:
y.grad_fn

In [28]:
z = y * y * 3
out = z.mean()

In [29]:
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [30]:
out.backward()

In [31]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [14]:
x = torch.randn(2, 2)
a = (x * 3) / (x - 1)

In [15]:
x, a

(tensor([[ 0.3462, -0.6242],
         [ 0.7840,  1.2841]]), tensor([[ -1.5882,   1.1530],
         [-10.8859,  13.5583]]))

In [16]:
a.requires_grad

False

In [17]:
a.requires_grad_(True)

tensor([[ -1.5882,   1.1530],
        [-10.8859,  13.5583]], requires_grad=True)

In [18]:
a.requires_grad

True

In [19]:
b = (a * a).sum()

In [20]:
b.grad_fn

In [32]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

y

tensor([1134.0945, -839.3181, 1068.2760], grad_fn=<MulBackward0>)